### ISSUE TITLE
mac打开页签搜索框不能获取焦点

### ISSUE THREAD

**Issue by kukudeshengge** [wangfpp/chrome_theme#1]

**Comment by wangfpp** [comment]
一直没找到原因  每次都是浏览器的URL自动获取了焦点
我看其他类似的插件也有这个问题

**Comment by wangfpp** [comment]
确实解决不了这个问题
Google Chrome不让auto focus
https://stackoverflow.com/questions/16684663/chrome-27-new-tab-page-extension-cant-steal-focus-from-omnibox
